import { ReactNode } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'
import { Toaster } from '@/components/ui/toaster'
import AuthProvider from '@/components/auth-provider'
import { Header } from '@/components/header'
import { ReactQueryClientProvider } from '@/components/providers/react-query'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={cn(inter.className, '')}>
        <div className="">
          <Toaster />
          <AuthProvider>
            <ReactQueryClientProvider>
              <Header />
              {children}
            </ReactQueryClientProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  )
}
