import { ReactNode } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import { Navbar } from '../components/navbar/navbar'
import { cn } from '@/lib/utils'
import { Toaster } from '@/components/ui/toaster'
import AuthProvider from '@/components/auth-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'min-h-screen')}>
        <div className="min-h-screen">
          <Toaster />
          <AuthProvider>
            <Navbar />
            <main className="pb-12 pt-8">{children}</main>
          </AuthProvider>
        </div>
      </body>
    </html>
  )
}
